### ISSUE TITLE
Cannot make velox

### ISSUE THREAD

**Issue by Kinokoio** [michaelforney/velox#12] opened 2015-06-28 21:02 UTC
Tried to build velox using make but got the following error:

GEN	protocol/velox-client-protocol.h
make: *** No rule to make target '/usr/local/share/swc/swc.xml', needed by 'protocol/swc-client-protocol.h'.  Stop.

**Comment by michaelforney** [comment] 2015-07-02 02:36
Duplicate of #11.

**Closed by michaelforney** 2015-07-02 02:36 UTC
